### ISSUE TITLE
Shop is broken when self hosting

### ISSUE THREAD

**Issue by NightZan999** [BobDotCom/BobDotBot#27]
**Describe the bug**
You can't add more than one item in economy system. While self hosting when you try adding more than one item you get errors. 
SQLite Error:
```
Ignoring exception in command shop add:
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/container/cogs/economy/shop.py", line 73, in add
    await cursor.execute(f'ALTER TABLE users ADD COLUMN item{number} INTEGER;')
  File "/home/container/.local/lib/python3.8/site-packages/aiosqlite/cursor.py", line 37, in execute
    await self._execute(self._cursor.execute, sql, parameters)
  File "/home/container/.local/lib/python3.8/site-packages/aiosqlite/cursor.py", line 31, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
  File "/home/container/.local/lib/python3.8/site-packages/aiosqlite/core.py", line 122, in _execute
    return await future
  File "/home/container/.local/lib/python3.8/site-packages/aiosqlite/core.py", line 98, in run
    result = function()
sqlite3.OperationalError: duplicate column name: itemNone

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/container/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 903, in invoke
    await ctx.command.invoke(ctx)
  File "/home/container/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1329, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "/home/container/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 859, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/container/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: OperationalError: duplicate column name: itemNone
```
Why is this happening?

**Comment by BobDotCom** [comment]
Well for starters none of the code is really meant to be hosted in any bot besides the main one. Anyways this is probably happening because you didn't pass correct arguments to the command.

**Comment by ReyterYT** [comment]
well first of all it seems that the number you are providing on the f string is `None` and the query is attempting to add another column which already exists

**Comment by ReyterYT** [comment]
> Well for starters none of the code isn't really meant to be hosted in any bot besides the main one. Anyways this is probably happening because you didn't pass correct arguments to the command.

actually the argument is filled but the database result is `null` which explains why the column name is `itemNone` and it seems they are hosting on the bot itself they just mean selfhost which means hosting locally

**Comment by NightZan999** [comment]
So, I am passing in the wrong arguments?

**Comment by ReyterYT** [comment]
> So, I am passing in the wrong arguments?

no you did not but the database query returned `None` in `[-1][0]` thats the issue

**Comment by NightZan999** [comment]
That means rows[-1][0] doesn't exist. But how is that possible?

**Comment by ReyterYT** [comment]
> That means rows[-1][0] doesn't exist. But how is that possible? 

its possible because the column value can be `null`

**Comment by NightZan999** [comment]
Right, so in aiosqlite when you do rows = await cursor.fetchall() isn't the first index (i.e. [-1]) the last from the right. Which is the latest. In that the first index would be the ID of the item. Is this a bug with aiosqlite? Or are the indexes wrong?

**Comment by ReyterYT** [comment]
> Right, so in aiosqlite when you do rows = await cursor.fetchall() isn't the first index (i.e. [-1]) the last from the right. Which is the latest. In that the first index would be the ID of the item. Is this a bug with aiosqlite? Or are the indexes wrong? 

as i said the column value is `null` try and print rows before indexing them ```py
rows = await cursor.fetchall()
print(rows)
numbers = rows[-1][0]
```

**Comment by NightZan999** [comment]
k I fixed this, thanks @ReyterYT
