### ISSUE TITLE
use f strings.

### ISSUE THREAD

**Issue by Motzumoto** [BobDotCom/BobDotBot#28]
f srings.

**Comment by ReyterYT** [comment]
well there's like alot of ways for formatting strings so its not actually obligated to use f-strings :/

**Comment by mudkipdev** [comment]
> well there's like alot of ways for formatting strings so its not actually obligated to use f-strings :/

why no f srings???????????????????????????????????

but bob always forgets to do

**Comment by mudkipdev** [comment]
.format

**Comment by mudkipdev** [comment]
after he puts {}

**Comment by mudkipdev** [comment]
:/

**Comment by mudkipdev** [comment]
this should be fixed

**Comment by mudkipdev** [comment]
cuz bob forgets

**Comment by mudkipdev** [comment]
to format so fsrings better

**Comment by ReyterYT** [comment]
dude i use %s and .format and format() depend on how im formatting it smh

**Comment by mudkipdev** [comment]
Shut Up

**Comment by mudkipdev** [comment]
%s is outdated

**Comment by mudkipdev** [comment]
also .format is for specific use cases

**Comment by mudkipdev** [comment]
fs ring are better for most cases

**Comment by mudkipdev** [comment]
and let me tell you

**Comment by mudkipdev** [comment]
in bobs case

**Comment by mudkipdev** [comment]
its better

**Comment by mudkipdev** [comment]
for him to use

**Comment by mudkipdev** [comment]
fsrings

**Comment by ReyterYT** [comment]
right okay but again _not obligated_

**Comment by BobDotCom** [comment]
.format is an f string

**Comment by BobDotCom** [comment]
also im gonna rewrite my noob code when i get time

**Comment by ReyterYT** [comment]
> .format is an f string

what no, f-string literals have `f` at the beginning of the string while `.format()` is just a method from string to format the current string

**Comment by BobDotCom** [comment]
f string is short for formatted string, its almost the same thing, just a different way of ding it

**Comment by ChickenDevs** [comment]
Yeaa this issue is useless, closed
